version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
